### ISSUE TITLE
IAM role filter id ignored?

### ISSUE THREAD

**Issue by lvh** [jckuester/awsweeper#40]
Hi! I'm using awsweeper v0.3.2 (binary release off github) with the following config file:

```yaml
aws_ami:
aws_autoscaling_group:
aws_cloudformation_stack:
aws_ebs_snapshot:
aws_ebs_volume:
aws_efs_file_system:
aws_eip:
aws_elb:
aws_iam_group:
aws_iam_instance_profile:
aws_iam_policy:
aws_iam_role:
    - id: OrganizationAccountAccessRole
aws_iam_user:
aws_instance:
aws_internet_gateway:
aws_key_pair:
#aws_kms_alias:
#aws_kms_key:
aws_launch_configuration:
aws_nat_gateway:
aws_network_acl:
aws_network_interface:
aws_route53_zone:
aws_route_table:
aws_s3_bucket:
aws_security_group:
aws_subnet:
aws_vpc:
aws_vpc_endpoint:
```

The role with id `OrganizationAccountAccessRole` is deleted anyway. --dry-run shows `OrganizationAccountAccessRole` as the id of the resource, so it's not like the problem is it's secretly using an ARN as the id or anything.
