### ISSUE TITLE
Filters for all resource types

### ISSUE THREAD

**Issue by cloudlena** [jckuester/awsweeper#42]
It would be great if I could set a config for all supported resource types. An example config might be:

```yml
"*":
  - tags:
    environment: test
```

or

```yml
all:
  - tags:
    environment: test
```
