### ISSUE TITLE
Filter by relative date

### ISSUE THREAD

**Issue by cloudlena** [jckuester/awsweeper#43]
I would like to filter by a relative date instead of an absolute one. An example might be:

```yml
aws_instance:
  - created:
      before: 5d
```

This would delete all resources that are older than 5 days at the time of running `awsweeper`. We could use the standard Go terms like `5d`, `2h`, `2m` etc.
